esphome:
  name: evcp
  name_add_mac_suffix: true 

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

packages:
  logger:     !include common/logger.yaml
  wifi:       !include common/wifi.yaml
  ota:        !include common/ota.yaml
  api:        !include common/api.yaml
  web_server: !include common/web_server.yaml
  status:     !include common/status.yaml
  # mqtt:     !include common/mqtt.yaml

#############################################################################
light:
  - platform: esp32_rmt_led_strip
    id: led_strip
    name: "Light"
    num_leds: 1
    rgb_order: GRB
    pin: GPIO7
    rmt_channel: 0
    chipset: WS2812
    restore_mode: ALWAYS_OFF
    default_transition_length: 0.5sec

  - platform: partition
    name: "LED 1"
    id: led_1
    default_transition_length: 0.5sec
    segments:
      - id: led_strip
        from: 0
        to: 0

binary_sensor:
  - platform: homeassistant
    name: "Relay ${relay_id} Status"
    id: relay_1_status
    entity_id: switch.relay_${relay_id}
    on_press:
     - light.turn_on:
         id: led_1
         brightness: 60%
         red:   0
         green: 1
         blue:  0
    on_release:
     - light.turn_off:
         id: led_1

