esphome:
  name: ev-charger


esp32:
#  board: esp32-s3-devkitc-1
 board: heltec_wifi_lora_32_V3
 variant: esp32s3
 framework:
   type: arduino
   version: 2.0.9
   #version: 2.0.10
   platform_version: 6.4.0
   #platform_version: 6.4.0

packages:
  logger:     !include common/logger.yaml
  wifi:       !include common/wifi.yaml
  ota:        !include common/ota.yaml
  api:        !include common/api.yaml
  web_server: !include common/web_server.yaml
  status:     !include common/status.yaml
  # mqtt:     !include common/mqtt.yaml
  
#############################################################################
  
external_components:
#  - source:
#      type: git
#      url: https://github.com/PaulSchulz/ev-charging-scheduler-esphome
#      ref: master
  - source:
      type: local
      path: components
    components: ["ev_scheduler"]
      
switch:
  - platform: gpio
    pin: 34
    id: relay_1
    name: Relay_1
  - platform: gpio
    pin: 33
    id: relay_2
    name: Relay_2
  - platform: gpio
    pin: 47
    id: relay_3
    name: Relay_3
  - platform: gpio
    pin: 48
    id: relay_4
    name: Relay_4

ev_scheduler: 
  id: my_scheduler
#  pin: 7
#  switches:
#    - id: relay_1
#    - id: relay_2
#    - id: relay_3
#    - id: relay_4
