esphome:
  name: ev-charger
  platform: ESP32
  board: esp32dev

external_components:
  - source:
      type: git
      url: https://github.com/PaulSchulz/ev-charging-scheduler-esphome
      ref: main  # Change this to the correct branch/tag

logger:

switch:
  - platform: gpio
    pin: 18
    id: relay_1
  - platform: gpio
    pin: 19
    id: relay_2
  - platform: gpio
    pin: 21
    id: relay_3
  - platform: gpio
    pin: 22
    id: relay_4

ev_scheduler:
  id: my_scheduler
  switches:
    - id: relay_1
    - id: relay_2
    - id: relay_3
    - id: relay_4
