esphome:
  name: ev-charger

esp32:
#  board: esp32-s3-devkitc-1
 board: heltec_wifi_lora_32_V3
 variant: esp32s3
 framework:
   type: arduino
   version: 2.0.9
   #version: 2.0.10
   platform_version: 6.4.0
   #platform_version: 6.4.0

packages:
  logger:     !include common/logger.yaml
  wifi:       !include common/wifi.yaml
  ota:        !include common/ota.yaml
  api:        !include common/api.yaml
  web_server: !include common/web_server.yaml
  status:     !include common/status.yaml
  # mqtt:     !include common/mqtt.yaml

  ev_scheduler: !include ev_scheduler.yaml
  
#############################################################################
external_components:
  - source:
      type: local
      path: components
    components: ["ev_scheduler"]


