esphome:
  name: evcs
  name_add_mac_suffix: true 

esp32:
# board: heltec_wifi_lora_32_V3
#   variant: esp32s3
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    #version: 2.0.9
    #version: 2.0.10
    #platform_version: 6.4.0
# framework:
#   type: esp-idf
##  Note: Does not support 'rmt_channel" setting in "esp32_rmt_led_strip"
##  Nore: Does not support 'millis()' function.

packages:
  logger:     !include common/logger.yaml
  wifi:       !include common/wifi.yaml
  ota:        !include common/ota.yaml
  api:        !include common/api.yaml
  web_server: !include common/web_server.yaml
  status:     !include common/status.yaml
  # mqtt:     !include common/mqtt.yaml

  ev_scheduler: !include ev_scheduler.yaml

ev_scheduler:
  schedule_interval: 10sec
  
#############################################################################
external_components:
  - source:
      type: local
      path: components
    components: ["ev_scheduler"]

light:
  - platform: esp32_rmt_led_strip
    id: led_strip
    name: "Light"
    num_leds: 4
    rgb_order: GRB
    pin: GPIO7
    rmt_channel: 0
    chipset: WS2812
    restore_mode: ALWAYS_OFF
    default_transition_length: 0.5sec

  - platform: partition
    name: "LED 1"
    id: led_1
    default_transition_length: 0.5sec
    segments:
      - id: led_strip
        from: 0
        to: 0

  - platform: partition
    name: "LED 2"
    id: led_2
    default_transition_length: 0.5sec
    segments:
      - id: led_strip
        from: 1
        to: 1

  - platform: partition
    name: "LED 3"
    id: led_3
    default_transition_length: 0.5sec
    segments:
      - id: led_strip
        from: 2
        to: 2

  - platform: partition
    name: "LED 4"
    id: led_4
    default_transition_length: 0.5sec
    segments:
      - id: led_strip
        from: 3
        to: 3

binary_sensor:
  - platform: switch
    name: "Relay 1 Status"
    id: relay_1_status
    source_id: relay_1
    on_press:
     - light.turn_on:
         id: led_1
         brightness: 60%
         red:   0
         green: 1
         blue:  0
    on_release:
     - light.turn_off:
         id: led_1

  - platform: switch
    name: "Relay 2 Status"
    id: relay_2_status
    source_id: relay_2
    on_press:
     - light.turn_on:
         id: led_2
         brightness: 60%
         red:   0
         green: 1
         blue:  0
    on_release:
     - light.turn_off:
         id: led_2

  - platform: switch
    name: "Relay 3 Status"
    id: relay_3_status
    source_id: relay_3
    on_press:
     - light.turn_on:
         id: led_3
         brightness: 60%
         red:   0
         green: 1
         blue:  0
    on_release:
     - light.turn_off:
         id: led_3

  - platform: switch
    name: "Relay 4 Status"
    id: relay_4_status
    source_id: relay_4
    on_press:
     - light.turn_on:
         id: led_4
         brightness: 60%
         red:   0
         green: 1
         blue:  0
    on_release:
     - light.turn_off:
         id: led_4
